// LOGIN
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// VTC ACTIONS
export const FETCH_VTCS = 'FETCH_VTCS';
export const NEW_VTC = 'NEW_VTC';
export const DELETE_VTC = 'DELETE_VTC';
export const EDIT_VTC = 'EDIT_VTC';
export const UPDATE_VTC = 'UPDATE_VTC';
export const SELECT_VTC = 'SELECT_VTC';

// CONTAINER ACTIONS
export const FETCH_CONTAINERS = 'FETCH_CONTAINERS';
export const FETCH_CONTAINER_TYPE = 'FETCH_CONTAINER_TYPE';
export const NEW_CONTAINER = 'NEW_CONTAINER';
export const DELETE_CONTAINER = 'DELETE_CONTAINER';
export const EDIT_CONTAINER = 'EDIT_CONTAINER';
export const UPDATE_CONTAINER = 'UPDATE_CONTAINER';
export const SELECT_CONTAINER = 'SELECT_CONTAINER';